minimum_pre_commit_version: 4.0.1
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1"
    hooks:
      - id: prettier
        files: '^(?!mlflow/pypi_package_index.json|docs/|mlflow/server/js/).+\.(js|md|json|ya?ml)$'
        args: ["--no-config", "--print-width", "100"]
        require_serial: true
